{
 "title": "template_service",
 "description": "Vertx Sample Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "template_service_system_cpu_usage"
    }
   ]
  },
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Health Check Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "template_service_HealthCheckCount_total"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "template_service_vertx_http_server_connections",
     "legendFormat": "{{local}}"
    }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(template_service_vertx_http_server_requestCount_total[1m])) by (local,code,path), 0.001)"
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(template_service_vertx_http_server_requestCount_total[1m])) by (local,code,path), 0.001)"
    }
   ]
  },
  {
   "title": "Global response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(template_service_vertx_http_server_responseTime_seconds_sum[1m])) / sum(irate(template_service_vertx_http_server_responseTime_seconds_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(template_service_vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(template_service_vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_service_vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(template_service_vertx_http_server_responseTime_seconds_sum[1m])) by (path) / sum(irate(template_service_vertx_http_server_responseTime_seconds_count[1m])) by (path)",
     "legendFormat": "{{path}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(template_service_vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path))",
     "legendFormat": "{{path}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_service_vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path))",
     "legendFormat": "{{path}} [99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(template_service_vertx_http_server_bytesSent_sum[1m])) / sum(rate(template_service_vertx_http_server_bytesSent_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(template_service_vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(template_service_vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_service_vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(template_service_vertx_http_server_bytesReceived_sum[1m])) / sum(rate(template_service_vertx_http_server_bytesReceived_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(template_service_vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(template_service_vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_service_vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "template_service_vertx_eventbus_handlers",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "template_service_vertx_eventbus_pending",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(template_service_vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(template_service_vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(template_service_vertx_eventbus_sent_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(template_service_vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(template_service_vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(template_service_vertx_eventbus_received_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(template_service_vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(template_service_vertx_eventbus_processingTime_seconds_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(template_service_vertx_eventbus_processingTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(template_service_vertx_eventbus_processingTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_service_vertx_eventbus_processingTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus processing time by address",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(template_service_vertx_eventbus_processingTime_seconds_sum[1m])) by (address) / sum(irate(template_service_vertx_eventbus_processingTime_seconds_count[1m])) by (address)",
     "legendFormat": "{{address}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(template_service_vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address))",
     "legendFormat": "{{address}} [med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(template_service_vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address))",
     "legendFormat": "{{address}} [95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_service_vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address))",
     "legendFormat": "{{address}} [99p]"
    }
   ]
  }
 ]
}